// main/src/pages/_components/Footer.svelte
<script>


</script>

<main class="mb-10 md:mb-0 bg-bg_white text-bg_black dark:bg-super_black dark:text-bg_white h-[145px] flex justify-center items-center">
    <section>
    <div class="text-center my-4">
        <div class="flex font-semibold text-xs justify-center">
          <a href="#about" class="mx-6 dark:hover:text-snow_white hover:text-super_black">About</a>
          <a href="#portfolio" class="mx-6 dark:hover:text-snow_white hover:text-super_black">Projects</a>
          <a href="#services" class="mx-6 dark:hover:text-snow_white hover:text-super_black">Services</a>
        </div>
        <div class="flex justify-center text-xl my-4">
          <a href="instagram"><i class="fab fa-instagram hover:text-super_black mx-6 md:mx-8  dark:hover:text-snow_white"></i></a>
          <a href="facebook"><i class="fab fa-facebook hover:text-super_black mx-6 md:mx-8  dark:hover:text-snow_white"></i></a>
          <a href="linkedIn"><i class="fab fa-linkedin hover:text-super_black mx-6 md:mx-8  dark:hover:text-snow_white"></i></a>
          <a href="linkedIn"><i class="fab fa-twitter hover:text-super_black mx-6 md:mx-8  dark:hover:text-snow_white"></i></a>
          <a href="linkedIn"><i class="fab fa-youtube hover:text-super_black mx-6 md:mx-8  dark:hover:text-snow_white"></i></a>

        </div>
        <p class="text-xs mt-2">&copy; 2023 Unicorn. All rights reserved.</p>
      </div> 
    </section> 
</main>

// main/src/components/Footer.vue
<template>
  <div class="footer border border-t color-bg_white">
    <h1 class="text-3xl font-semibold my-4 text-center">Zai</h1>
    <div class="text-center my-2">
      <div class="flex font-semibold text-xs justify-center">
        <a href="#about" class="mx-4">About</a>
        <a href="#portfolio" class="mx-4">Projects</a>
        <a href="#services" class="mx-4">Services</a>
      </div>
      <div class="flex justify-center text-xl my-3">
        <a href="#"><i class="fab fa-instagram mx-4"></i></a>
        <a href="#"><i class="fab fa-facebook mx-4"></i></a>
        <a href="#"><i class="fab fa-linkedin mx-4"></i></a>
      </div>
      <p class="text-xs mt-2">&copy; 2023 Your Company. All rights reserved.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Footer",
});
</script>

<style></style>
