// main/src/components/ProjectDetail.vue
<template>
  <div
    class="fixed top-0 left-0 right-0 bottom-0 flex justify-center items-center bg-black bg-opacity-50 z-50">
    <div class="bg-white p-6 rounded-md shadow-md lg:w-[1000px] sm:[800px]">
      <h2 class="text-2xl font-bold mb-4 text-center">Details</h2>
      <p class="text-lg mb-6">{{ detail }}</p>
      <button class="bg-red-500 text-white py-2 px-4 rounded" @click="close">
        Close
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ProjectDetail",
  props: ["detail"],
  mounted() {
    document.body.classList.add("disable-scrollbar");
  },
  beforeUnmount() {
    document.body.classList.remove("disable-scrollbar");
  },
  methods: {
    close() {
      this.$emit("close");
    },
  },
});
</script>

<style>
.disable-scrollbar {
  overflow: hidden;
}
</style>

// main/src/pages/_components/details/ProjectDetail.svelte
<script>
    export let item;
    export let close;

    document.body.classList.add("disable-scrollbar");

    const handleClose = ()=>{
        close()
        document.body.classList.remove("disable-scrollbar")
    }


</script>


<div
class="fixed top-0 left-0 right-0 bottom-0 flex justify-center items-center backdrop-filter backdrop-blur z-50 px-2">
<div
  class="mt-8 bg-snow_white dark:bg-super_black px-6 pb-6 pt-4 rounded-3xl shadow-md lg:w-[600px] w-[350px] md:w-[500px] min-h-[400px] text-secondary_bold">
  <div class="flex justify-end m-0 p-0">
    <button class="" on:click={handleClose}>
      <i class="fas fa-xmark"></i>
    </button>
  </div>

  <main>
    <h1>{item.name}</h1>
  </main>


</div>
</div>
