// main/src/pages/HomePage.vue
<template>
  <section class="hpage flex items-center">
    <div class="container mx-auto sm:pt-8">
      <div class="grid grid-cols-1 md:grid-cols-12 gap-8">
        <div class="col-span-1 md:col-span-8">
          <h1 class="text-2xl md:text-4xl font-bold text-primary">
            Sai Yell Yint Aung
          </h1>
          <h3 class="text-primary font-semibold">Full-Stack Web Developer</h3>
          <p class="text-secondary mt-4">
            I'm a Full-Stack developer with a passion for creating exceptional
            web experiences. Currently based in Myanmar.
          </p>
          <div class="flex mt-4">
            <button
              class="bg-primary hover:bg-gray-900 text-white py-4 text-sm px-4 rounded-xl">
              Contact Me<i class="fas fa-light fa-paper-plane mx-2"></i>
            </button>
          </div>
        </div>
        <div class="col-span-1 md:col-span-3 bg-neutral-950"></div>
        <div class="col-span-1 md:col-span-1">
          <div
            class="social-links flex flex-wrap justify-start items-center space-x-3">
            <div class="md:my-4 ml-3">
              <a :href="linkedIn" class="social-icon">
                <i class="fab fa-linkedin text-2xl"></i>
              </a>
            </div>
            <div class="md:my-4">
              <a :href="github" class="social-icon">
                <i class="fab fa-github text-2xl"></i>
              </a>
            </div>
            <div class="md:my-4">
              <a :href="twitter" class="social-icon">
                <i class="fab fa-twitter text-2xl"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import links from "../assets/datas/links";

export default defineComponent({
  name: "HomePage",
  data() {
    return {
      twitter: links.twitter,
      github: links.gitGub,
      linkedIn: links.linkedIn,
    };
  },
});
</script>

<style scoped>
.hpage {
  height: 100vh;
  padding: 0 1rem;
}

.container {
  max-width: 960px;
}

.social-icon {
  @apply inline-flex items-center justify-center w-10 h-10 rounded-full bg-bg_white text-primary hover:bg-gray-300;
}

.bg-neutral-950 {
  @apply bg-gray-900;
}
</style>

// main/src/pages/home/HomePage.svelte
<div id="home" class="flex justify-center md:items-center items-start w-full min-h-[70vh] md:min-h-screen pt-14">
    <main class="container max-w-full md:max-w-[1000px] px-3 md:px-6 flex flex-col md:flex-row-reverse justify-between ">
        <div class="flex gap-3 md:gap-8">
            <div class="w-[260px] h-[260px] block bg-white "></div>
            <div class="flex flex-col justify-around text-bg_white text-xl md:text-2xl ">
                <a href="/" class='p-1 rounded-full dark:hover:text-snow_white '><i class="fab fa-twitter "></i></a>
                <a href="/" class='p-1 rounded-full dark:hover:text-snow_white '><i class="fab fa-linkedin "></i></a>
                <a href="/" class='p-1 rounded-full dark:hover:text-snow_white '><i class="fab fa-github "></i></a>
                <a href="/" class='p-1 rounded-full dark:hover:text-snow_white '><i class="fab fa-youtube "></i></a>
            </div>
        </div>

        <div class="flex-1 md:pr-6 leading-6 mt-8 md:mt-0">
            <h1 class="font-bold text-primary text-3xl md:text-5xl mb-1">
                Sai Yell Yint Aung
            </h1>
            <h3 class='text-base md:text-lg mb-4 md:mb-6 font-medium text-white'>
                Crafting Code and Ventures with Purpose
            </h3>
            <p class="text-sm md:text-base md:pr-6 mb-5 text-bg_white">
                Stepping into the Realm Where Innovation and Purpose Converge. A Visionary Journey of Crafting Code, Cultivating Transformative Ventures, and Illuminating a Path to Redefine the Future.
            </p>
            <button class="w-40 py-3 bg-primary text-bg_white font-semibold rounded-sm hover:text-snow_white" >
                Contact Me <i class="fas fa-light fa-paper-plane ml-2"></i>
            </button>

        </div>
    </main>
</div>
